# Generated by Django 2.0.3 on 2018-04-03 17:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20180403_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bank.Budget'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 4, 3, 17, 19, 43, 115369, tzinfo=utc), verbose_name='Date'),
        ),
    ]
