# Generated by Django 2.0.3 on 2018-04-05 07:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20180403_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='person',
        ),
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='bank.Month'),
        ),
        migrations.AddField(
            model_name='budget',
            name='prevision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='budget',
            name='spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 4, 5, 7, 58, 9, 478846, tzinfo=utc), verbose_name='Date'),
        ),
    ]
