# Generated by Django 2.0.3 on 2018-04-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20180405_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
