# Generated by Django 2.0.1 on 2018-03-19 15:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20180314_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.CharField(choices=[('RE', 'Restos'), ('MA', 'Market'), ('CH', 'Charges'), ('HB', 'Hors Budget')], default='HB', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 3, 19, 15, 2, 32, 975069, tzinfo=utc), verbose_name='Date'),
        ),
    ]
