# Generated by Django 2.0.3 on 2018-04-05 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_budgetname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bank.BudgetName'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bank.BudgetName'),
        ),
    ]
