# Generated by Django 2.0.1 on 2018-03-19 15:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20180319_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='budget',
            field=models.CharField(choices=[('Restos', 'Restos'), ('Market', 'Market'), ('Charges', 'Charges'), ('HB', 'Hors Budget')], default='HB', max_length=2),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 3, 19, 15, 57, 26, 106144, tzinfo=utc), verbose_name='Date'),
        ),
    ]
