# Generated by Django 2.0.3 on 2018-04-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_auto_20180410_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='check',
            field=models.NullBooleanField(default=False),
        ),
    ]
