# Generated by Django 2.0.1 on 2018-03-27 10:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_auto_20180324_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day', models.DateField(verbose_name='First Day')),
                ('last_day', models.DateField(verbose_name='Last Day')),
                ('total_input', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_output', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 3, 27, 10, 17, 15, 15901, tzinfo=utc), verbose_name='Date'),
        ),
    ]
