# Generated by Django 2.0.3 on 2018-04-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_auto_20180430_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
