# Generated by Django 2.0.3 on 2018-04-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_auto_20180430_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='check',
            field=models.BooleanField(),
        ),
    ]
